--- a/runit-2.1.2/src/Makefile 2014-08-10 20:22:35.000000000 +0200
+++ b/runit-2.1.2/src/Makefile 2016-02-14 20:32:46.939989208 +0100
a/runit-2.1.2/man/runsv.8
@@ -234,7 +234,7 @@
 
 hasshsgr.h: chkshsgr choose compile hasshsgr.h1 hasshsgr.h2 load \
 tryshsgr.c warn-shsgr
-	./chkshsgr || ( cat warn-shsgr; exit 1 )
+	./chkshsgr || ( cat warn-shsgr )
 	./choose clr tryshsgr hasshsgr.h1 hasshsgr.h2 > hasshsgr.h
 
 haswaitp.h: choose compile haswaitp.h1 haswaitp.h2 load trywaitp.c
